school/results/urls.py
from .views import Homepage
from django.urls import path,re_path
from django.conf import settings



from .views import StudentDetails, StudentAdd, ResultUpdate, StudentUpdateView, StudentAddmarks, student_add_marks, Pdf, SubjectSeaechView, SubjectDetailView, AllRankViewSearch, TeacherAllView, TeacherDetailView,SummaryView
urlpatterns = [
    path('', Homepage.as_view(), name='home'),

    path('subject-search/', SubjectSeaechView.as_view(), name='subject_search'),

    path('class_wise_rank_search/', AllRankViewSearch.as_view(
        template_name='results/all_rank_search.html'), name='all_rank_search'),

    re_path(r'^(?P<pk>\d+)/subject-detail/$', SubjectDetailView.as_view(), name='subject_details'),

    re_path(r'^(?P<pk>\d+)/student-result-details/$', StudentDetails.as_view(), name='std_details'),

    path('student_add/', StudentAdd.as_view(), name='std_add'),
    re_path(r'student_update/(?P<pk>\d+)/$', StudentUpdateView.as_view(), name='std_update'),

    re_path(r'student_marks_add/(?P<pk>\d+)/$', StudentAddmarks.as_view(), name='std_add_marks'),


    re_path(r"std_add_marks_func/(?P<pk>\d+)/$", student_add_marks, name='stdAdd_marks'),

    re_path(r"std_marks_update/(?P<pk>\d+)/$",ResultUpdate.as_view(), name='stdmarks_update'),

    re_path(r'^(?P<pk>\d+)/get-print-result-sheet/',Pdf.as_view(), name='pdf'),

    path('teacher_list/', TeacherAllView.as_view(), name='teacher_list'),

    re_path(r'^(?P<pk>\d+)/teachers-profile/', TeacherDetailView.as_view(), name='teacher_detail'),

    path('summary/', SummaryView.as_view(), name='summary'),
    

    
]

school/school/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from results.views import Homepage, RankListView
from results.api.views import UserViewSet
from django.contrib.auth import views as auth_views

from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static

#router = routers.DefaultRouter()
#router.register(r'users', UserViewSet)





#from django.contrib.auth import login
#from django.contrib.auth import authenticate, login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Homepage.as_view(), name='home_app'),
    path('results/', include('results.urls')),
    #path('login/', auth_views.login, name='login1'),
    path('results/', include('django.contrib.auth.urls')),
    path('api/', UserViewSet.as_view(), name='api'),
    #re_path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    path('all-school-rank/',RankListView.as_view() , name='rank'),

]

handler404 = 'results.views.ErrorPage'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
school_name = 'Fulhata Secondary School'

# default: "Django Administration"
admin.site.site_header = school_name+' Admin Panel'
# default: "Site administration"
admin.site.index_title = school_name+' Administration '
admin.site.site_title = school_name+' adminsitration'

school/results/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from .grade_sheet import SubjectGrade, SubjectGradePoint
from django.utils import timezone

from django.db.models import Avg, Count, Min, Sum


STD_CLASS = (
    ('6', 'Six'),
    ('7', 'Seven'),
    ('8', 'Eight'),
    ('9', 'Nine'),
    ('10', 'Ten'),
)


STD_GENDER = (
    ('MALE', 'Male'),
    ('FEMALE', 'Female'),
)

STD_GROUP = (
        ('S', 'Science'),
        ('B', 'Business Studies'),
        ('H', 'Humatics'),
        ('G', 'General')
)


REGULAR = 'R'
OPTIONAL = 'O'

SUBJECT_TYPE_CHOICE = (
        (REGULAR, 'REGULAR'),
        (OPTIONAL, 'OPTIONAL')
)






class CustomUser(AbstractUser):
    name=models.CharField('Full Name',max_length=100)



class StdCommon(models.Model):
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True



class SubjectTecher(StdCommon):
    teacher_name=models.CharField('Teacher Name', max_length=100)
    teach_phone_number=models.IntegerField('Mobile Number')
    teach_major_subject=models.CharField('Subject Name: ', max_length=100)


    def __str__(self):
        return self.teacher_name



class StdSubject(StdCommon):


    subject_name = models.CharField('Subject Name', max_length=100)
    teacher=models.ForeignKey(SubjectTecher, on_delete=models.CASCADE, related_name='teacher')
    subject_group = models.CharField(
        'Subject Group', choices=STD_GROUP, default='G', max_length=10)

    subject_code=models.CharField('Subject Code', max_length=10)
    subjet_class = models.CharField(
        'Subject Class', max_length=2, choices=STD_CLASS, default='6')
    subject_type = models.CharField(
        'Subject Type', max_length=1, default=REGULAR, choices=SUBJECT_TYPE_CHOICE)
    subject_full_marks = models.DecimalField(
        'Full Marks', max_digits=5, decimal_places=2, default=100,blank=True, null=True)



    subject_theory_full_marks = models.FloatField('Theory Marks', blank=True, null=True)
    subject_mcq_full_marks = models.FloatField('MCQ', blank=True, null=True)
    subject_practical_marks = models.FloatField('Practical', blank=True, null=True)
    subject_total_marks = models.FloatField('Total Marks', blank=True, null=True, help_text='Plz dont input any number')

    '''
        Bangla and English first 2nd part marks added
    '''

    first_part_name = models.CharField('First Subject Name', max_length=100, blank=True, null=True)
    first_part_theory_full_marks = models.FloatField('First Part Theory Marks', blank=True, null=True)
    first_part_mcq_full_marks = models.FloatField('First Part MCQ Marks', blank=True, null=True)

    second_part_name = models.CharField('Second Subject Name', max_length=100, blank=True, null=True)
    second_part_theory_full_marks = models.FloatField(
        'Second Part Theory Marks', blank=True, null=True)
    second_part_mcq_full_marks = models.FloatField('Second MCQ Marks', blank=True, null=True)


    first_second_full_marks = models.FloatField('1st and 2nd Part Total marks', blank=True, null=True)






    subject_form_searh_name=models.CharField('Subject Search Form name', max_length=500, blank=True, null=True)


    def __str__(self):
        return self.subject_name+' Class '+self.subjet_class+' '+' '+self.subject_type+' Code '+self.subject_code


    def save(self, *args, **kwargs):
        subject_form_searh_name=self.subject_name+' Class '+self.subjet_class+' '+' '+self.subject_type+' Code '+self.subject_code

        self.subject_form_searh_name=subject_form_searh_name


        try:
            self.subject_full_marks = self.subject_theory_full_marks
            theory_full=self.subject_theory_full_marks
        except:
            self.subject_full_marks = 0
            self.subject_theory_full_marks=None
            theory_full=0

        if self.subject_theory_full_marks == None:
            self.subject_theory_full_marks = None


        '''
        MCQ Marks added
        '''
        try:
            if self.subject_full_marks==None:
                self.subject_full_marks=0
            self.subject_full_marks = self.subject_full_marks + self.subject_mcq_full_marks
        except:
            if self.subject_full_marks==None:
                self.subject_full_marks=0
            self.subject_full_marks = self.subject_full_marks


        '''

        Practical Marks

        '''

        try:
            self.subject_full_marks = self.subject_full_marks + self.subject_practical_marks
        except:
            self.subject_full_marks = self.subject_full_marks

        self.subject_total_marks = self.subject_full_marks


        if self.subject_total_marks == None or self.subject_total_marks ==0:
            '''
            First and 2nd part adding marks

        '''
            try:
                self.first_second_full_marks=self.first_part_theory_full_marks
                try:
                    self.first_second_full_marks = self.first_second_full_marks+ self.first_part_mcq_full_marks
                except:
                    self.first_second_full_marks = self.first_second_full_marks
            except:
                self.first_second_full_marks = self.first_second_full_marks

            if self.first_second_full_marks != None:
                try:
                    self.first_second_full_marks = self.first_second_full_marks + self.second_part_theory_full_marks

                except:
                   self.first_second_full_marks = self.first_second_full_marks


                try:
                    self.first_second_full_marks = self.first_second_full_marks+ self.second_part_mcq_full_marks
                except:
                    self.first_second_full_marks = self.first_second_full_marks

                self.subject_total_marks = self.first_second_full_marks

            elif self.first_second_full_marks == None:
                self.first_second_full_marks == None

            self.subject_total_marks = self.subject_total_marks
            self.subject_full_marks=self.subject_total_marks



        super(StdSubject, self).save(*args, **kwargs) # Call the real save() method

    class Meta:
        verbose_name = ("Subject")
        verbose_name_plural = ("Subject")
        ordering = ['subject_code']

class StudentInfo(StdCommon):




    std_name = models.CharField('Student Name',max_length=100, help_text='Type only student Full Name like as Nazmul Islam or Nazrul Islam', blank=True, null=True)
    std_class = models.CharField('Student Class',max_length=2, choices=STD_CLASS, default=10, help_text='Select a class')
    std_roll = models.IntegerField('Roll Number',help_text='Type Student Roll Number (Only Number)')
    std_group=models.CharField('Group', choices=STD_GROUP, max_length=1, default='G')
    std_gender=models.CharField('Gender', max_length=10, choices=STD_GENDER, default='MALE')
    #std_subjects = models.ManyToManyField(StdSubject)


    std_total_marks = models.FloatField('Total Marks', default=0, blank=True, null=True)
    std_marks_with_fail_sub = models.FloatField(
        'Total Marks', default=0, blank=True, null=True)

    std_gpa = models.CharField('GPA', max_length=50,default='F', blank=True, null=True)

    std_grade_point_total_sum=models.FloatField('Total Avg Number per Subject', blank=True, null=True) # toal grade point sum

    std_grade_point_total_subject_avg = models.FloatField(
        'Total GPA', blank=True, null=True) #avg gradepoint

    std_fail_subject=models.IntegerField('Fail Subject', blank=True, null=True)


    school_rank=models.IntegerField('Student Rank in School',default=0, blank=True, null=True)
    class_rank = models.IntegerField(
        'Student Rank in Class', default=0, blank=True, null=True)



    def __str__(self):
        return self.std_name

    class Meta:
            verbose_name = ("Student Detail")
            verbose_name_plural = ("Student Detail's")
            ordering = ['std_roll']


    def total_marks_sum(self):
        std_id = self.id
        x = Marks.objects.filter(std_name=std_id).aggregate(
            total_number=Sum('subject_marks')).get('total_number', 0)

        return x


    def save(self, *args, **kwargs):

        std_id = self.id
        fail_sub = 0
        std_result='Pass'

        total_number = Marks.objects.filter(std_name=std_id).aggregate(
            total_number=Sum('subject_marks')).get('total_number', 0)
        self.std_marks_with_fail_sub = Marks.objects.filter(std_name=std_id).aggregate(
             total_number_f=Sum('subject_total_marks')).get('total_number_f', 0)

        subject_grade = ((Marks.objects.filter(std_name=std_id, subject_gradepoint__gte=1).aggregate(sp=Sum('subject_gradepoint')).get('sp', 0)))



        self.std_total_marks = total_number

        if subject_grade is None:
            subject_grade=0


        self.std_grade_point_total_sum = subject_grade

        subject_grade_f = Marks.objects.filter(std_name=std_id, subject_name__subject_type__startswith='R')
        absent_check_f = Marks.objects.filter(std_name=std_id)




        try:
            class_rank_new = Rank.objects.get(std=self.id)
            self.class_rank = class_rank_new.class_rank
            self.school_rank = class_rank_new.school_rank
        except :
            self.class_rank = 0
            self.school_rank = 0


        for i in subject_grade_f:

            if 'F' == i.subject_gpa:
                fail_sub = fail_sub+1

        if fail_sub >= 1:
            std_result = 'Fail ' +str(fail_sub)+' Subject'
            #self.std_gpa = std_result



        self.std_fail_subject=fail_sub

        if fail_sub >= 1:
            self.std_grade_point_total_subject_avg=0

        else:
            if self.std_class == '6' or self.std_class == '7':
                self.std_grade_point_total_subject_avg ='%2f' % (subject_grade/7)

school/results/forms.py
from django import forms
from .models import StudentInfo, Marks, StdSubject
from django.forms import inlineformset_factory

class ProfileSearchForm(forms.Form):
    std_class = forms.CharField(required=False)




class AddStudentInfo(forms.ModelForm):
    class Meta:
        model=StudentInfo
        fields=("__all__")



class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model=StudentInfo

        fields=("__all__")

    
class StudentSubjectGPAForm(forms.ModelForm):
    class Meta:
        model = Marks

        exclude = ('std_name', 'subject_gpa',
                   'subject_gradepoint', 'std_result')

    
class StudentSubjectGPAFormAdd(forms.ModelForm):
    class Meta:
        model = Marks
        exclude = ('std_name','subject_gpa',
                   'subject_gradepoint', 'std_result')

    def __init__(self, *args, **kwargs):
        super(StudentSubjectGPAFormAdd, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['subject_marks'].queryset = StudentInfo.objects.filter(
                std_name__exact=self.instance.id)


class Addmarks(forms.Form):
   #students = forms.ModelChoiceField(queryset=StudentInfo.objects.get(pk=27))
   subject = forms.ModelChoiceField(queryset=StdSubject.objects.all())
   marks = forms.IntegerField()





''

class ResultSearchForm(forms.Form):
    STD_CLASS = (
        ('6', 'Six'),
        ('7', 'Seven'),
        ('8', 'Eight'),
        ('9', 'Nine'),
        ('10', 'Ten'),
    )

    std_roll_form = forms.IntegerField(label="Roll Number",min_value=1, max_value=99)
    std_class_form = forms.ChoiceField(choices=STD_CLASS, label="Select Class")







class SubjectSearchForm(forms.Form):
    STD_CLASS = (
        ('6', 'Six'),
        ('7', 'Seven'),
        ('8', 'Eight'),
        ('9', 'Nine'),
        ('10', 'Ten'),
    )
    subject_name=forms.ModelChoiceField(queryset=StdSubject.objects.all(), label='Select Subject Name', empty_label=None)
    subject_class = forms.ChoiceField(choices=STD_CLASS, label="Select Class")


class ClassSearchForm(forms.Form):
    STD_CLASS = (
        ('6', 'Six'),
        ('7', 'Seven'),
        ('8', 'Eight'),
        ('9', 'Nine'),
        ('10', 'Ten'),
    )

    student_class = forms.ChoiceField(choices=STD_CLASS, label="Select Class")

school/results/api/views.py
from .serializers import StudentSerializers
from results.models import StudentInfo
from rest_framework import viewsets
from rest_framework import generics
from rest_framework.permissions import IsAdminUser



class UserViewSet(generics.ListAPIView):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = StudentInfo.objects.all().order_by('-std_grade_point_total_subject_avg','std_roll')
    serializer_class = StudentSerializers
    #permission_classes = (IsAdminUser,)

school/results/templates/results/pdf.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load humanize %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{object.std_name}} Exam Result Report</title>



    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
            font-family: 'Amita';font-size: 19px;
            font-family: 'Allura';font-size: 19px;
            font-family: 'Actor';font-size: 19px;
            font-family: 'Actor';font-size: 19px;
        }
        body {
            font-family: 'Actor';font-size: 19px;
			border:1px solid #000;
			padding:10px 5px 10px 5px;
        }
        p,button,h1,h2,h3,h4,h5{
            font-family: 'Amiko';font-size: 17px;
        }
        .title_custom{
            font-family: 'Amita';font-size: 32px;font-weight: 35px;
        }
        .title_custom_two{
            font-family: 'Almendra';font-size: 22px;
        }
        th{
            font-size: 8px;
			text-align: left;
        }
        td{
            font-size: 9.5px;
        }


 table, th,td{ border-spacing: 5px; border: .5px solid black; } table, th, td { border: 1px solid black; border-collapse: collapse;
} th, td { padding: 5px; } th { text-align: left; }




}
 .watermark { width: 100px; height: 100px; display: block; position: relative; }
.watermark::after { content: ""; background:url({%static 'results/img/logo.png' %});background-repeat:no-repeat; opacity:
0.10; top: 0;
left: 0; bottom: 0; right: 0; position: absolute; z-index: -1; background-attachment: fixed; background-position: center;
}

#background{ position:absolute; z-index:0; background; display:block; min-height:10%; min-width:10%; color:yellow;
} #content{ position:absolute; z-index:1; }
#bg-text {margin-top: 200px;
     color:lightgrey; font-size:15px; margin-left:250px;
}

table#mytable, table#mytable td { border: none !important; font-size: 14px; line-height: 22px}


#container{width:100%; text-align:center; margin-bottom: 30px}

#left
{ float:left; width:200px; height: 20px; background: # }
#center{ display: inline-block; margin:0 auto; width:200px; height: 20px; background:}
 #right
 { float:right; width:160px;
height: 20px; background: # }


    </style>
</head>

<body>




	<div class="" style="width:90%;margin:0 auto">
        <div id="background">
<p id="bg-text">{{object.std_name}} {{object.std_roll}} {{object.get_std_group_display}} {{object.get_std_class_display}}</p>



        </div>

        <div class="watermark">

        </div>


		<div class="">
            <div>
                <img style="width:100px;height:101px;margin-left:8%;margin-top:1%;" src="{%static 'results/img/logo.png' %}" alt="">
                <h1 style="text-align:center;font-size:20px;margin-top:-17%" class="title_custom">
                    Fulhata Secondary School
                </h1>
                <p style="text-align:center;font-size:12px; margin-top:-15px">Morrelganj, Bagerhat</p>




                <p style="text-align:center;font-size:12px; margin-top:-15px" class="">
                    Eiin No: 115030, Founded: 1946
                    <br> Contact: fulhatahs@gmail.com, Morrelganj, Bagerhat

                </p>


            </div>
        </div>

<p class="new_css" style="text-align:center;font-size:16px">
 {% if object.std_class == '10' %} Pre Test Examination 2018  {% else %} Half Yearly Examination 2018 {% endif %}
 Result Card
</p>




<hr>


<div class="" style="width:800px;display:block">

<div class="left_sideback" style="width:335px;float: left;overflow:hidden;display:block">

<table id="mytable">

                <tbody>
                    <tr>
                        <td>Full Name</td>
                        <td>: {{object.std_name}}</td>

                    </tr>
                    <tr>
                        <td>Gender</td>
                        <td>: {{object.get_std_gender_display}}</td>

                    </tr>

                    <tr >
                        <td>Class Roll</td>
                        <td>: {{object.std_roll}}</td>

                    </tr>
                    <tr >
                        <td>Class</td>
                        <td>: {{object.get_std_class_display}}</td>

                    </tr>

                    <tr >
                        <td>Group</td>
                        <td>: {{object.get_std_group_display}}</td>

                    </tr>

                    {% if ranks.class_rank < object.std_roll %}
                        <tr >
                        <td>Class Rank- {{object.get_std_class_display}}</td>
                        <td style="color:royalblue">: {{ranks.class_rank|ordinal}}
                        Rank Up

                        </td>
                        </tr>

                        {% elif ranks.class_rank == object.std_roll %}
                        <tr >
                            <td>Class Rank- {{object.get_std_class_display}}</td>

                            <td style="color:blue">: {{ranks.class_rank|ordinal}} Rank Label

                            </td>
                        </tr>


                        {% elif ranks.class_rank > object.std_roll %}
                        <tr >
                            <td>Class Rank- {{object.get_std_class_display}}</td>
                            <td style="color:red">: {{ranks.class_rank|ordinal}} Rank Down

                            </td>
                        {% endif %}
                        </tr>



                        <tr >
                            <td>School Rank</td>
                            <td>: {{ranks.school_rank|ordinal}}</td>

                        </tr>


                </tbody>
            </table>



</div>













<div style="width:400px;float:right;overflow:hidden;display:inline-block">





    <table border="0" style="width:55%!important">

            <tbody>


                <tr class="table-success">
                    {% if fail >= 1 %}
                    <td>Total Marks - Fail</td>
                    <td style="color:red">{{ total_marks_with_fail_sub|floatformat}}

                    </td>




                    {% else %}
                    <td>Total Marks</td>
                    <td>{{ total_marks_with_fail_sub|floatformat}} </td>

                    {% endif %}


                </tr>





                <tr class="table-success">
                    <td>Maximum Number</td>
                    <td style="font-size:10px">{{subject_max_number}}</td>

                </tr>
                <tr class="table-warning">
                    <td>Average Number</td>
                    <td>{{sub_avg_number|floatformat}}</td>

                </tr>
                <tr class="table-danger">
                    <td>Lowest Number</td>
                    <td style="font-size:10px">{{subject_min_number}}</td>

                </tr>


            </tbody>
        </table>
 </div>

</div>





 <div class="" style="width:60%;margin-top:240px;margin-left:auto;margin-right:auto;text-align:center;border:1px solid black">


        {% if fail >= 1 %}
        <p style="font-size:12px" >Result : Fail {{fail}} Subject</p>



        {% else %}
        <p style="font-size:12px">Result
            {% if toatal_grade_point > 5 %}
            <b>

            GPA- {{toatal_grade_point | floatformat:0}} (out of 5) All Subject A+ | Total
            Marks- {{ total_marks|floatformat}}
            </b>
            {% else %}

            GPA- {{toatal_grade_point | floatformat:2}} (out of 5) | Total
            Marks- {{ total_marks|floatformat}}

            {% endif %}

        </p>

        {% endif %}

 </div>






<div class="row">
    <div style="margin-top:20px">
        {% if object.marks_set.all %}




            <table style="width:100%" style="text-align:center:9px;padding:14px;border-spacing: 15px;"  class="table_sheet">
            <thead>
                <tr>
                    <th rowspan="2">No</th>
                    <th style="text-align:center" rowspan="2">Subject Code</th>
                    <th style="text-align:center" rowspan="2">Subject Name</th>
                    <th style="text-align:center" rowspan="2">Full Marks</th>
                    <th  style="text-align:center" colspan="4">Marks</th>

                    <th rowspan="4">Grade Point</th>
                    <th rowspan="4">Grade</th>
                </tr>
                <tr>
                    <th>Theory</th>
                    <th>MCQ</th>
                    <th>Practical</th>
                    <th>Total</th>

                </tr>
            </thead>
            <tbody>
                {% for i in object.marks_set.all %}
                <tr class="table_sheet">
                    <td>{{forloop.counter}}</td>

                    <td>{{i.subject_name.subject_code}}</td>

                    <!--subject name with fail style-->
                    {% if i.subject_gpa == "F" %}
                    <td style="text-align:left;color:red">
                        {% if i.subject_name.subject_type == 'O' %} {{i.subject_name.subject_name}}
                        <span style="font-size:7px!important;font-style:italic">({{i.subject_name.get_subject_type_display}})</span>
                        {% else %} {% if i.subject_name.first_part_name%} {{i.subject_name.subject_name}} {{i.subject_name.first_part_name}}
                        <br> {{i.subject_name.subject_name}} {{i.subject_name.second_part_name}} {% else %} {{i.subject_name.subject_name}} {% endif%}
                        {% endif %}
                    </td>
                    {% else %}
                    <td style="text-align:left">
                        {% if i.subject_name.subject_type == 'O' %} {{i.subject_name.subject_name}}
                        <span style="font-size:11px;font-style:italic">({{i.subject_name.get_subject_type_display}})</span>
                        {% else %} {% if i.subject_name.first_part_name%} {{i.subject_name.subject_name}} {{i.subject_name.first_part_name}}
                        <br> {{i.subject_name.subject_name}} {{i.subject_name.second_part_name}} {% else %} {{i.subject_name.subject_name}} {% endif%}
                        {% endif %}
                    </td>
                    {% endif %}
                    <!--end subject name with fail style-->


                    <td>{{i.subject_name.subject_full_marks|floatformat}}</td>


                    <td style="text-align:center">{{i.subject_theory|floatformat}}
                    {% if i.first_part_theory %}
                    {{i.first_part_theory|floatformat}}
                    {% endif %}  {% if i.second_part_theory %}
                    <br>
                    {{i.second_part_theory|floatformat}}
                    {% endif %}
                    </td>



                    <td style="text-align:center">{{i.subject_mcq|floatformat}}
                    {% if i.first_part_mcq %}

                    {{i.first_part_mcq|floatformat}}

                    {% endif %} {% if i.second_part_mcq %}
                    <br>
                    {{i.second_part_mcq|floatformat}}
                    {% endif %}
                    </td>


                    <td style="text-align:center">{{i.subject_practical|floatformat}}</td>
                    <td style="text-align:center">{{i.subject_total_marks|floatformat}}</td>





                    <td style="text-align:center"> {{i.subject_gradepoint|floatformat}}</td>

                    {% if i.subject_gpa == "F" %}
                    <td style="color:red;text-align:center">{{i.subject_gpa}}</td>
                    {% else %}
                    <td style="text-align:center">{{i.subject_gpa}}</td>
                    {% endif %}

                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <p>no update</p>
        {% endif %}



        <div id="container" style="clear:both">
            <hr>
            <div id="left">
                    <p style="font-size:12px">Result checked by</p>
                    <p style="font-size:11px;margin-top:-12px">Md. Bellal Hossain</p>
                    <p style="font-size:9px;margin-top:-13px">
                        <i>Asst. Teacher (Agriculture)</i>
                    </p>
            </div>
            <div id="center">
                    <p style="font-size:12px">Class teacher</p>
                    <p style="font-size:11px;margin-top:-12px"></p>
                    <p style="font-size:9px;margin-top:-13px">

                    </p>
            </div>

            <div id="right">
                <p style="font-size:12px">Head of the institute</p>
            </div>
        </div>






        <div style="display:block;">
            <p style="font-size:8px">
 App Developed & Maintained by
<a style="color:black;text-decoration:none" href="https://web.facebook.com/asadlive.sohel1">Asaduzzaman Sohel</a><br>
<i>Print Time: {{time}}</i>

            </p>

            <p style="font-size:8px" class="m-0 text-center text-white">
            </p>

        </div>


    </div>
</div>






        </div>
    </div>



	</div>







</body>

</html>

school/results/templates/results/std_add_marks_func.html
{% extends "results/base.html" %} {% load crispy_forms_tags %} {% block main_content %}

<h2>Hey this is work</h2>

<p>Gender: {{std.std_gender}}</p>
<p>Roll: {{std.std_roll}}</p>
<p>Class: {{std.std_class}}</p>
<p>Group: {{std.std_group}}</p>


<div class="col-md-6 offset-md-3  centered">
    <form action="" method="POST">
        {% csrf_token %} {{form | crispy}}

        <input type="submit" value="Add Your Subject" class="btn btn-primary">
    </form>
</div>
ff{{x}} {% endblock main_content %}

school/results/templates/results/std_marks_update.html
{% extends "results/base.html" %} {% block main_content %}


{{form}}


{% endblock main_content %}